[api_keys]
os_names          = "YOUR_OS_DATA_HUB_API_KEY"
epc_bearer_token  = "YOUR_EPC_BEARER_TOKEN"
companies_house   = "YOUR_COMPANIES_HOUSE_API_KEY"

[paths]
ofcom_db = "data/ofcom.db"
uprn_db  = "data/uprn.db"
